version: '3'
services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      - MYSQL_DATABASE=cafeapp
      - MYSQL_USER=shinma
      - MYSQL_PASSWORD=0103
      - MYSQL_ROOT_PASSWORD=0103
    
    volumes:
    - ./data:/var/lib/mysql

    ports:
    - 3306:3306

  web:
    build: .
    command: sh -c "sleep 10 && python3 manage.py runserver 0.0.0.0:8000" #mysqlコンテナの起動を待つためコマンドを10秒遅延
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
