version: '3.8'
services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=cafeapp
      - MYSQL_USER=shinma
      - MYSQL_PASSWORD=0103
      - MYSQL_ROOT_PASSWORD=0103
    
    volumes:
    - ./data:/var/lib/mysql

    ports:
    - 3306:3306

  web:
    build: .
    command: ./combined_script.sh
    volumes:
      - .:/cafeapp
    ports:
      - "8000:8000"
    depends_on:
      - mysql