# Generated by Django 5.1.15 on 2026-01-03 10:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='メニュー名')),
                ('img', models.ImageField(upload_to='menu/', verbose_name='メニュー画像')),
                ('alt', models.CharField(max_length=50, verbose_name='画像タイトル')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='値段(円)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'メニュー',
                'verbose_name_plural': 'メニュー',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
                ('date', models.DateField(verbose_name='日付')),
                ('time', models.TimeField(verbose_name='時間')),
                ('email', models.EmailField(max_length=40, null=True, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(max_length=15, verbose_name='電話番号')),
                ('number_of_people', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='人数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['date', 'time'], name='pages_booki_date_b6ded1_idx'), models.Index(fields=['-created_at'], name='pages_booki_created_ae2466_idx')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('', 'カテゴリーを選択'), ('promotion', 'お店の紹介'), ('irregularmenu', '期間限定メニュー'), ('event', 'イベント'), ('talk', 'お客様との会話')], max_length=100, verbose_name='カテゴリー')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('img', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='画像')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='画像タイトル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'ニュース',
                'verbose_name_plural': 'ニュース',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='pages_news_created_a517e3_idx'), models.Index(fields=['category'], name='pages_news_categor_59feb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評価')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.menu', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'レビュー',
                'verbose_name_plural': 'レビュー',
                'ordering': ['-date_posted'],
            },
        ),
    ]
